version: '2'
services:
  crawler:
    image: web_crawler
    build:
      dockerfile: Dockerfile
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: web_crawler
    restart: always